// Auto-generated by semrush-snapshot.sh -- do not edit manually
// Last updated: 2026-03-22

export interface SnapshotEntry {
  date: string;
  organicKeywords: number;
  organicTraffic: number;
  organicCost: number;
  rank: number;
}

export const snapshotHistory: SnapshotEntry[] = [
  {
    date: "2026-03-17",
    organicKeywords: 35,
    organicTraffic: 529,
    organicCost: 698,
    rank: 0,
  },
  {
    date: "2026-03-19",
    organicKeywords: 35,
    organicTraffic: 529,
    organicCost: 698,
    rank: 1592910,
  },
  {
    date: "2026-03-20",
    organicKeywords: 35,
    organicTraffic: 529,
    organicCost: 698,
    rank: 1592993,
  },
  {
    date: "2026-03-21",
    organicKeywords: 35,
    organicTraffic: 529,
    organicCost: 698,
    rank: 1592930,
  },
  {
    date: "2026-03-22",
    organicKeywords: 37,
    organicTraffic: 529,
    organicCost: 698,
    rank: 1593413,
  },
];

export const lastUpdated = "2026-03-22";
